import { createFileRoute, Link } from "@tanstack/react-router";
import { useState, useMemo } from "react";
import { PageHeader } from "@/components/PageHeader";
import { formatRupiah, uploadToCloudinary } from "@/lib/utils";
import { useAjuanList, useCreatePencairan, usePencairan, useDeletePencairan, useSettings, useUpdatePencairan } from "@/lib/queries";
import { useAuth } from "@/lib/auth-context";
import { Search, Wallet, CheckCircle2, Upload, X, Building2, User, Calendar, Loader2, Trash2, History, Eye, Download, Pencil } from "lucide-react";
// Route generated by antigravity
import { toast } from "sonner";
import type { LucideIcon } from "lucide-react";
import jsPDF from "jspdf";

export const Route = createFileRoute("/pencairan/")({
  head: () => ({ meta: [{ title: "Pencairan Dana — E-Budgeting Pesantren" }] }),
  component: PencairanPage,
});

const banks = ["Bank Syariah Indonesia (BSI)", "Bank Muamalat", "Bank Mandiri", "Bank Riau Kepri Syariah", "BCA Syariah"];

function PencairanPage() {
  const { data: ajuanData = [] } = useAjuanList();
  const { user, role } = useAuth();
  const create = useCreatePencairan();
  const { data: historyData = [], isLoading: loadingHistory } = usePencairan();
  const { data: settings } = useSettings("instansi");
  const deletePc = useDeletePencairan();
  const [activeTab, setActiveTab] = useState<"proses" | "riwayat">("proses");
  const disetujui = useMemo(() => ajuanData.filter(a => a.status === "disetujui" || a.status === "dicairkan"), [ajuanData]);
  const [q, setQ] = useState("");
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [metode, setMetode] = useState<"tunai" | "transfer">("tunai");
  const [bank, setBank] = useState(banks[0]);
  const [norek, setNorek] = useState("");
  const [pemilik, setPemilik] = useState("");
  const [buktiFile, setBuktiFile] = useState<File | null>(null);
  const [buktiPreview, setBuktiPreview] = useState<string | null>(null);
  const [buktiPenyerahanFile, setBuktiPenyerahanFile] = useState<File | null>(null);
  const [buktiPenyerahanPreview, setBuktiPenyerahanPreview] = useState<string | null>(null);
  const [busy, setBusy] = useState(false);

  const found = disetujui.filter(a => `${a.kode} ${a.judul}`.toLowerCase().includes(q.toLowerCase()));
  const selected = ajuanData.find(a => a.id === selectedId) ?? disetujui[0];

  const submit = async () => {
    if (!selected || !user) return;
    if (selected.status === "dicairkan") { toast.error("Ajuan ini sudah dicairkan"); return; }
    if (metode === "transfer" && (!norek.trim() || !pemilik.trim())) { 
      toast.error("Lengkapi nomor rekening dan nama pemilik untuk transfer"); return; 
    }
    setBusy(true);
    let bukti_url: string | undefined;
    let bukti_penyerahan_url: string | undefined;
    try {
      if (buktiFile) bukti_url = await uploadToCloudinary(buktiFile, settings);
      if (buktiPenyerahanFile) bukti_penyerahan_url = await uploadToCloudinary(buktiPenyerahanFile, settings);

      await create.mutateAsync({
        ajuan_id: selected.id, 
        metode,
        bank: metode === "transfer" ? bank : undefined, 
        no_rekening: metode === "transfer" ? norek : undefined, 
        nama_pemilik: metode === "transfer" ? pemilik : undefined,
        jumlah: Number(selected.total), 
        bukti_url,
        bukti_penyerahan_url,
      });
      toast.success(`Pencairan ${selected.kode} berhasil`);
      setNorek(""); setPemilik(""); 
      setBuktiFile(null); setBuktiPreview(null);
      setBuktiPenyerahanFile(null); setBuktiPenyerahanPreview(null);
    } catch (e) {
      toast.error("Gagal", { description: (e as Error).message });
    } finally { setBusy(false); }
  };

  const downloadKwitansi = (h: any) => {
    const doc = new jsPDF();
    doc.setFontSize(18);
    doc.text("KWITANSI PENYERAHAN DANA", 105, 20, { align: "center" });
    doc.setFontSize(10);
    doc.text("PESANTREN MODERN RAUDHATUSSALAM MAHATO", 105, 28, { align: "center" });
    doc.line(20, 32, 190, 32);
    doc.setFontSize(12);
    doc.text(`No. Referensi : ${h.kode}`, 20, 45);
    doc.text(`Tanggal        : ${new Date(h.created_at).toLocaleDateString("id-ID")}`, 20, 52);
    doc.text("Telah diserahkan dana untuk keperluan:", 20, 65);
    doc.setFont("helvetica", "bold");
    doc.text(h.judul, 20, 72);
    doc.setFont("helvetica", "normal");
    doc.text(`Sebesar :`, 20, 85);
    doc.setFontSize(16);
    doc.setFont("helvetica", "bold");
    doc.text(formatRupiah(Number(h.jumlah)), 45, 85);
    doc.setFontSize(12);
    doc.setFont("helvetica", "normal");
    doc.text("Penerima,", 150, 105, { align: "center" });
    doc.text(`( ${h.nama_pemilik || h.pengaju_nama || "................."} )`, 150, 135, { align: "center" });
    doc.save(`Kwitansi_${h.kode}.pdf`);
  };

  return (
    <>
      <PageHeader title="Pencairan Dana" description="Proses pencairan untuk ajuan yang telah disetujui" />

      <div className="mb-6 flex items-center gap-1 rounded-xl border border-border bg-card p-1 shadow-soft">
        <button onClick={() => setActiveTab("proses")} className={`flex-1 flex items-center justify-center gap-2 rounded-lg px-4 py-2 text-sm font-semibold ${activeTab === "proses" ? "bg-primary text-primary-foreground" : "hover:bg-secondary"}`}>
          <Wallet className="h-4 w-4" /> Proses Pencairan
        </button>
        <button onClick={() => setActiveTab("riwayat")} className={`flex-1 flex items-center justify-center gap-2 rounded-lg px-4 py-2 text-sm font-semibold ${activeTab === "riwayat" ? "bg-primary text-primary-foreground" : "hover:bg-secondary"}`}>
          <History className="h-4 w-4" /> Riwayat Pencairan
        </button>
      </div>

      {activeTab === "proses" ? (
        <div className="grid gap-6 lg:grid-cols-3">
          <div className="lg:col-span-1">
            <div className="rounded-2xl border border-border bg-card p-4 shadow-soft">
              <div className="relative mb-3">
                <Search className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
                <input value={q} onChange={e => setQ(e.target.value)} placeholder="Cari kode ajuan..." className="h-10 w-full rounded-lg border border-input bg-background pl-9 pr-3 text-sm outline-none focus:border-ring focus:ring-2 focus:ring-ring/20" />
              </div>
              <p className="px-1 pb-2 text-[11px] font-semibold uppercase tracking-wider text-muted-foreground">Ajuan disetujui</p>
              <ul className="scrollbar-thin max-h-[480px] space-y-1.5 overflow-y-auto">
                {found.length === 0 ? <li className="rounded-lg p-4 text-center text-sm text-muted-foreground">Tidak ada ajuan disetujui</li> : found.map(a => (
                  <li key={a.id}>
                    <button onClick={() => setSelectedId(a.id)} className={`w-full rounded-lg border p-3 text-left transition-all ${selected?.id === a.id ? "border-primary bg-primary-soft" : "border-border hover:bg-secondary/60"}`}>
                      <div className="flex items-center justify-between">
                        <p className="font-mono text-xs font-semibold">{a.kode}</p>
                        {a.status === "dicairkan" && <CheckCircle2 className="h-4 w-4 text-info" />}
                      </div>
                      <p className="mt-1 truncate text-sm font-semibold">{a.judul}</p>
                      <p className="mt-0.5 text-xs text-primary">{formatRupiah(Number(a.total))}</p>
                    </button>
                  </li>
                ))}
              </ul>
            </div>
          </div>

          <div className="space-y-6 lg:col-span-2">
            {selected ? (
              <>
                <div className="rounded-2xl border border-border bg-card p-6 shadow-soft">
                  <div className="mb-4 flex items-center gap-3">
                    <div className="flex h-12 w-12 items-center justify-center rounded-xl bg-primary text-primary-foreground"><Wallet className="h-5 w-5" /></div>
                    <div>
                      <p className="font-mono text-xs font-semibold text-muted-foreground">{selected.kode}</p>
                      <h3 className="font-bold">{selected.judul}</h3>
                    </div>
                  </div>

                  <div className="grid gap-6 md:grid-cols-2">
                    <div className="space-y-4">
                      <div>
                        <label className="mb-1.5 block text-xs font-semibold">Metode Pencairan</label>
                        <div className="grid grid-cols-2 gap-2">
                          <button onClick={() => setMetode("tunai")} className={`flex h-10 items-center justify-center gap-2 rounded-lg border text-sm font-bold transition-all ${metode === "tunai" ? "border-primary bg-primary-soft text-primary" : "border-border hover:bg-secondary"}`}>
                            <Wallet className="h-4 w-4" /> TUNAI
                          </button>
                          <button onClick={() => setMetode("transfer")} className={`flex h-10 items-center justify-center gap-2 rounded-lg border text-sm font-bold transition-all ${metode === "transfer" ? "border-primary bg-primary-soft text-primary" : "border-border hover:bg-secondary"}`}>
                            <Building2 className="h-4 w-4" /> TRANSFER
                          </button>
                        </div>
                      </div>

                      {metode === "transfer" && (
                        <>
                          <div className="md:col-span-2">
                            <label className="mb-1.5 block text-xs font-semibold">Bank Tujuan</label>
                            <select value={bank} onChange={e => setBank(e.target.value)} className="h-10 w-full rounded-lg border border-input bg-background px-3 text-sm outline-none focus:border-ring focus:ring-2 focus:ring-ring/20">
                              {banks.map(b => <option key={b}>{b}</option>)}
                            </select>
                          </div>
                          <div className="md:col-span-2">
                            <label className="mb-1.5 block text-xs font-semibold">Nomor Rekening Tujuan</label>
                            <input value={norek} onChange={e => setNorek(e.target.value)} placeholder="0000000000" className="h-10 w-full rounded-lg border border-input bg-background px-3 text-sm outline-none focus:border-ring focus:ring-2 focus:ring-ring/20" />
                          </div>
                          <div className="md:col-span-2">
                            <label className="mb-1.5 block text-xs font-semibold">Nama Pemilik Rekening / Instansi</label>
                            <input value={pemilik} onChange={e => setPemilik(e.target.value)} placeholder="Nama pada buku tabungan" className="h-10 w-full rounded-lg border border-input bg-background px-3 text-sm outline-none focus:border-ring focus:ring-2 focus:ring-ring/20" />
                          </div>
                        </>
                      )}

                      <div className="md:col-span-2">
                        <label className="mb-1.5 block text-xs font-semibold">Lampiran Dokumen Anggaran (Disetujui)</label>
                        {buktiPreview ? (
                          <div className="relative inline-block">
                            <img src={buktiPreview} alt="Dokumen" className="max-h-44 rounded-lg border border-border" />
                            <button onClick={() => { setBuktiPreview(null); setBuktiFile(null); }} className="absolute -top-2 -right-2 flex h-7 w-7 items-center justify-center rounded-full bg-destructive text-destructive-foreground shadow-soft"><X className="h-4 w-4" /></button>
                          </div>
                        ) : (
                          <label className="flex cursor-pointer flex-col items-center gap-2 rounded-xl border-2 border-dashed border-border bg-secondary/30 p-6 text-center transition-all hover:bg-secondary/50">
                            <div className="flex h-10 w-10 items-center justify-center rounded-full bg-primary/10 text-primary"><Upload className="h-5 w-5" /></div>
                            <p className="text-sm font-bold">Pilih Dokumen Anggaran</p>
                            <input type="file" accept="image/*,application/pdf" className="hidden" onChange={e => { const f = e.target.files?.[0]; if (f) { setBuktiFile(f); setBuktiPreview(URL.createObjectURL(f)); } }} />
                          </label>
                        )}
                      </div>

                      <div className="md:col-span-2">
                        <label className="mb-1.5 block text-xs font-semibold">Bukti Penyerahan Dana (Foto/Scan)</label>
                        {buktiPenyerahanPreview ? (
                          <div className="relative inline-block">
                            <img src={buktiPenyerahanPreview} alt="Bukti Penyerahan" className="max-h-44 rounded-lg border border-border" />
                            <button onClick={() => { setBuktiPenyerahanPreview(null); setBuktiPenyerahanFile(null); }} className="absolute -top-2 -right-2 flex h-7 w-7 items-center justify-center rounded-full bg-destructive text-destructive-foreground shadow-soft"><X className="h-4 w-4" /></button>
                          </div>
                        ) : (
                          <label className="flex cursor-pointer flex-col items-center gap-2 rounded-xl border-2 border-dashed border-border bg-amber-50/30 p-6 text-center transition-all hover:bg-amber-50/50">
                            <div className="flex h-10 w-10 items-center justify-center rounded-full bg-amber-100 text-amber-600"><Upload className="h-5 w-5" /></div>
                            <p className="text-sm font-bold">Unggah Foto Penyerahan</p>
                            <input type="file" accept="image/*" className="hidden" onChange={e => { const f = e.target.files?.[0]; if (f) { setBuktiPenyerahanFile(f); setBuktiPenyerahanPreview(URL.createObjectURL(f)); } }} />
                          </label>
                        )}
                      </div>
                    </div>
                    <div className="mt-6 flex justify-end gap-2 border-t border-border pt-6">
                      <button onClick={submit} disabled={busy} className="inline-flex h-12 w-full items-center justify-center gap-2 rounded-xl bg-primary px-6 text-sm font-bold text-primary-foreground shadow-soft transition-all hover:bg-primary/90 disabled:opacity-50">
                        {busy ? <Loader2 className="h-4 w-4 animate-spin" /> : <CheckCircle2 className="h-5 w-5" />} 
                        Konfirmasi & Selesaikan Pencairan
                      </button>
                    </div>
                  </div>
                </div>
              </>
            ) : (
              <div className="rounded-2xl border border-border bg-card p-12 text-center text-muted-foreground">
                Belum ada ajuan yang disetujui untuk dicairkan.
              </div>
            )}
          </div>
        </div>
      ) : (
        <div className="rounded-2xl border border-border bg-card shadow-soft overflow-x-auto">
          <table className="w-full text-sm text-left">
            <thead className="bg-secondary/50 text-muted-foreground">
              <tr className="uppercase text-[10px] font-black tracking-widest">
                <th className="px-4 py-3">Kode / Judul</th>
                <th className="px-4 py-3">Tujuan Transfer</th>
                <th className="px-4 py-3 text-right">Jumlah</th>
                <th className="px-4 py-3">Status</th>
                <th className="px-4 py-3 text-right">Aksi</th>
                <th className="px-4 py-3">Tanggal</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-border">
              {loadingHistory ? (
                <tr><td colSpan={6} className="p-12 text-center"><Loader2 className="mx-auto h-6 w-6 animate-spin text-primary" /></td></tr>
              ) : historyData.length === 0 ? (
                <tr><td colSpan={6} className="p-12 text-center text-muted-foreground">Belum ada riwayat pencairan.</td></tr>
              ) : historyData.map(h => (
                <tr key={h.id} className="hover:bg-secondary/30 transition-colors">
                  <td className="px-4 py-3">
                    <p className="font-mono text-xs font-semibold">{h.kode}</p>
                    <p className="font-medium truncate max-w-[200px]">{h.judul}</p>
                  </td>
                  <td className="px-4 py-3">
                    {h.metode === "transfer" ? (
                      <>
                        <p className="font-semibold">{h.bank}</p>
                        <p className="text-xs text-muted-foreground">{h.no_rekening} - {h.nama_pemilik}</p>
                      </>
                    ) : (
                      <span className="inline-flex items-center gap-1.5 font-bold text-amber-600">
                        <Wallet className="h-3 w-3" /> TUNAI / CASH
                      </span>
                    )}
                  </td>
                  <td className="px-4 py-3 text-right font-bold text-primary">{formatRupiah(Number(h.jumlah))}</td>
                  <td className="px-4 py-3">
                    <span className={`inline-flex rounded-full px-2 py-0.5 text-[10px] font-bold uppercase ${h.status === "selesai" ? "bg-success/10 text-success" : "bg-info/10 text-info"}`}>
                      {h.status}
                    </span>
                  </td>
                   <td className="px-4 py-3 text-right">
                    <div className="flex justify-end gap-1">
                      <Link 
                        to="/pencairan/$id"
                        params={{ id: h.id }}
                        className="p-2 text-info hover:bg-info/10 rounded-lg transition-colors flex items-center justify-center border border-info/20"
                        title="Detail Pencairan"
                      >
                        <Eye className="h-4 w-4" />
                      </Link>
                      <button 
                        onClick={() => downloadKwitansi(h)} 
                        className="p-2 text-primary hover:bg-primary/10 rounded-lg transition-colors flex items-center justify-center border border-primary/20" 
                        title="Unduh Kwitansi (PDF)"
                      >
                        <Download className="h-4 w-4" />
                      </button>
                      {(role === "admin" || role === "administrasi") && (
                        <>
                          <Link 
                            to="/pencairan/$id/edit" 
                            params={{ id: h.id }} 
                            className="p-2 text-amber-600 hover:bg-amber-100 rounded-lg transition-colors flex items-center justify-center border border-amber-200" 
                            title="Edit Pencairan"
                          >
                            <Pencil className="h-4 w-4" />
                          </Link>
                          <button 
                            onClick={() => {
                              if (confirm(`Batalkan pencairan untuk ${h.kode}? Status ajuan akan dikembalikan ke 'Disetujui'.`)) {
                                deletePc.mutate(h.id);
                              }
                            }}
                            className="p-2 text-destructive hover:bg-destructive/10 rounded-lg transition-colors flex items-center justify-center border border-destructive/20"
                          >
                            <Trash2 className="h-4 w-4" />
                          </button>
                        </>
                      )}
                    </div>
                  </td>
                  <td className="px-4 py-3 text-xs text-muted-foreground whitespace-nowrap">{new Date(h.created_at).toLocaleDateString("id-ID")}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
    </>
  );
}

function Info({ icon: Icon, label, value }: { icon: LucideIcon; label: string; value: string }) {
  return (
    <div className="flex items-center gap-2.5">
      <Icon className="h-4 w-4 text-muted-foreground" />
      <div className="min-w-0">
        <p className="text-[10px] font-semibold uppercase tracking-wider text-muted-foreground">{label}</p>
        <p className="truncate text-sm font-semibold">{value}</p>
      </div>
    </div>
  );
}
