/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PenggunaRouteImport } from './routes/pengguna'
import { Route as PengaturanRouteImport } from './routes/pengaturan'
import { Route as PencairanRouteImport } from './routes/pencairan'
import { Route as NotifikasiRouteImport } from './routes/notifikasi'
import { Route as LaporanRouteImport } from './routes/laporan'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as ApprovalRouteImport } from './routes/approval'
import { Route as AiRouteImport } from './routes/ai'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PencairanIndexRouteImport } from './routes/pencairan.index'
import { Route as LaporanIndexRouteImport } from './routes/laporan.index'
import { Route as AjuanIndexRouteImport } from './routes/ajuan.index'
import { Route as PenggunaBaruRouteImport } from './routes/pengguna_.baru'
import { Route as PencairanIdRouteImport } from './routes/pencairan.$id'
import { Route as LaporanBaruRouteImport } from './routes/laporan.baru'
import { Route as LaporanIdRouteImport } from './routes/laporan.$id'
import { Route as AjuanBaruRouteImport } from './routes/ajuan.baru'
import { Route as AjuanIdRouteImport } from './routes/ajuan.$id'
import { Route as PencairanIdEditRouteImport } from './routes/pencairan.$id.edit'

const PenggunaRoute = PenggunaRouteImport.update({
  id: '/pengguna',
  path: '/pengguna',
  getParentRoute: () => rootRouteImport,
} as any)
const PengaturanRoute = PengaturanRouteImport.update({
  id: '/pengaturan',
  path: '/pengaturan',
  getParentRoute: () => rootRouteImport,
} as any)
const PencairanRoute = PencairanRouteImport.update({
  id: '/pencairan',
  path: '/pencairan',
  getParentRoute: () => rootRouteImport,
} as any)
const NotifikasiRoute = NotifikasiRouteImport.update({
  id: '/notifikasi',
  path: '/notifikasi',
  getParentRoute: () => rootRouteImport,
} as any)
const LaporanRoute = LaporanRouteImport.update({
  id: '/laporan',
  path: '/laporan',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalRoute = ApprovalRouteImport.update({
  id: '/approval',
  path: '/approval',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PencairanIndexRoute = PencairanIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PencairanRoute,
} as any)
const LaporanIndexRoute = LaporanIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LaporanRoute,
} as any)
const AjuanIndexRoute = AjuanIndexRouteImport.update({
  id: '/ajuan/',
  path: '/ajuan/',
  getParentRoute: () => rootRouteImport,
} as any)
const PenggunaBaruRoute = PenggunaBaruRouteImport.update({
  id: '/pengguna_/baru',
  path: '/pengguna/baru',
  getParentRoute: () => rootRouteImport,
} as any)
const PencairanIdRoute = PencairanIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PencairanRoute,
} as any)
const LaporanBaruRoute = LaporanBaruRouteImport.update({
  id: '/baru',
  path: '/baru',
  getParentRoute: () => LaporanRoute,
} as any)
const LaporanIdRoute = LaporanIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => LaporanRoute,
} as any)
const AjuanBaruRoute = AjuanBaruRouteImport.update({
  id: '/ajuan/baru',
  path: '/ajuan/baru',
  getParentRoute: () => rootRouteImport,
} as any)
const AjuanIdRoute = AjuanIdRouteImport.update({
  id: '/ajuan/$id',
  path: '/ajuan/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PencairanIdEditRoute = PencairanIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => PencairanIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/approval': typeof ApprovalRoute
  '/audit': typeof AuditRoute
  '/auth': typeof AuthRoute
  '/laporan': typeof LaporanRouteWithChildren
  '/notifikasi': typeof NotifikasiRoute
  '/pencairan': typeof PencairanRouteWithChildren
  '/pengaturan': typeof PengaturanRoute
  '/pengguna': typeof PenggunaRoute
  '/ajuan/$id': typeof AjuanIdRoute
  '/ajuan/baru': typeof AjuanBaruRoute
  '/laporan/$id': typeof LaporanIdRoute
  '/laporan/baru': typeof LaporanBaruRoute
  '/pencairan/$id': typeof PencairanIdRouteWithChildren
  '/pengguna/baru': typeof PenggunaBaruRoute
  '/ajuan/': typeof AjuanIndexRoute
  '/laporan/': typeof LaporanIndexRoute
  '/pencairan/': typeof PencairanIndexRoute
  '/pencairan/$id/edit': typeof PencairanIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/approval': typeof ApprovalRoute
  '/audit': typeof AuditRoute
  '/auth': typeof AuthRoute
  '/notifikasi': typeof NotifikasiRoute
  '/pengaturan': typeof PengaturanRoute
  '/pengguna': typeof PenggunaRoute
  '/ajuan/$id': typeof AjuanIdRoute
  '/ajuan/baru': typeof AjuanBaruRoute
  '/laporan/$id': typeof LaporanIdRoute
  '/laporan/baru': typeof LaporanBaruRoute
  '/pencairan/$id': typeof PencairanIdRouteWithChildren
  '/pengguna/baru': typeof PenggunaBaruRoute
  '/ajuan': typeof AjuanIndexRoute
  '/laporan': typeof LaporanIndexRoute
  '/pencairan': typeof PencairanIndexRoute
  '/pencairan/$id/edit': typeof PencairanIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/approval': typeof ApprovalRoute
  '/audit': typeof AuditRoute
  '/auth': typeof AuthRoute
  '/laporan': typeof LaporanRouteWithChildren
  '/notifikasi': typeof NotifikasiRoute
  '/pencairan': typeof PencairanRouteWithChildren
  '/pengaturan': typeof PengaturanRoute
  '/pengguna': typeof PenggunaRoute
  '/ajuan/$id': typeof AjuanIdRoute
  '/ajuan/baru': typeof AjuanBaruRoute
  '/laporan/$id': typeof LaporanIdRoute
  '/laporan/baru': typeof LaporanBaruRoute
  '/pencairan/$id': typeof PencairanIdRouteWithChildren
  '/pengguna_/baru': typeof PenggunaBaruRoute
  '/ajuan/': typeof AjuanIndexRoute
  '/laporan/': typeof LaporanIndexRoute
  '/pencairan/': typeof PencairanIndexRoute
  '/pencairan/$id/edit': typeof PencairanIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai'
    | '/approval'
    | '/audit'
    | '/auth'
    | '/laporan'
    | '/notifikasi'
    | '/pencairan'
    | '/pengaturan'
    | '/pengguna'
    | '/ajuan/$id'
    | '/ajuan/baru'
    | '/laporan/$id'
    | '/laporan/baru'
    | '/pencairan/$id'
    | '/pengguna/baru'
    | '/ajuan/'
    | '/laporan/'
    | '/pencairan/'
    | '/pencairan/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai'
    | '/approval'
    | '/audit'
    | '/auth'
    | '/notifikasi'
    | '/pengaturan'
    | '/pengguna'
    | '/ajuan/$id'
    | '/ajuan/baru'
    | '/laporan/$id'
    | '/laporan/baru'
    | '/pencairan/$id'
    | '/pengguna/baru'
    | '/ajuan'
    | '/laporan'
    | '/pencairan'
    | '/pencairan/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/ai'
    | '/approval'
    | '/audit'
    | '/auth'
    | '/laporan'
    | '/notifikasi'
    | '/pencairan'
    | '/pengaturan'
    | '/pengguna'
    | '/ajuan/$id'
    | '/ajuan/baru'
    | '/laporan/$id'
    | '/laporan/baru'
    | '/pencairan/$id'
    | '/pengguna_/baru'
    | '/ajuan/'
    | '/laporan/'
    | '/pencairan/'
    | '/pencairan/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiRoute: typeof AiRoute
  ApprovalRoute: typeof ApprovalRoute
  AuditRoute: typeof AuditRoute
  AuthRoute: typeof AuthRoute
  LaporanRoute: typeof LaporanRouteWithChildren
  NotifikasiRoute: typeof NotifikasiRoute
  PencairanRoute: typeof PencairanRouteWithChildren
  PengaturanRoute: typeof PengaturanRoute
  PenggunaRoute: typeof PenggunaRoute
  AjuanIdRoute: typeof AjuanIdRoute
  AjuanBaruRoute: typeof AjuanBaruRoute
  PenggunaBaruRoute: typeof PenggunaBaruRoute
  AjuanIndexRoute: typeof AjuanIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pengguna': {
      id: '/pengguna'
      path: '/pengguna'
      fullPath: '/pengguna'
      preLoaderRoute: typeof PenggunaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pengaturan': {
      id: '/pengaturan'
      path: '/pengaturan'
      fullPath: '/pengaturan'
      preLoaderRoute: typeof PengaturanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pencairan': {
      id: '/pencairan'
      path: '/pencairan'
      fullPath: '/pencairan'
      preLoaderRoute: typeof PencairanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifikasi': {
      id: '/notifikasi'
      path: '/notifikasi'
      fullPath: '/notifikasi'
      preLoaderRoute: typeof NotifikasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laporan': {
      id: '/laporan'
      path: '/laporan'
      fullPath: '/laporan'
      preLoaderRoute: typeof LaporanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approval': {
      id: '/approval'
      path: '/approval'
      fullPath: '/approval'
      preLoaderRoute: typeof ApprovalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pencairan/': {
      id: '/pencairan/'
      path: '/'
      fullPath: '/pencairan/'
      preLoaderRoute: typeof PencairanIndexRouteImport
      parentRoute: typeof PencairanRoute
    }
    '/laporan/': {
      id: '/laporan/'
      path: '/'
      fullPath: '/laporan/'
      preLoaderRoute: typeof LaporanIndexRouteImport
      parentRoute: typeof LaporanRoute
    }
    '/ajuan/': {
      id: '/ajuan/'
      path: '/ajuan'
      fullPath: '/ajuan/'
      preLoaderRoute: typeof AjuanIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pengguna_/baru': {
      id: '/pengguna_/baru'
      path: '/pengguna/baru'
      fullPath: '/pengguna/baru'
      preLoaderRoute: typeof PenggunaBaruRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pencairan/$id': {
      id: '/pencairan/$id'
      path: '/$id'
      fullPath: '/pencairan/$id'
      preLoaderRoute: typeof PencairanIdRouteImport
      parentRoute: typeof PencairanRoute
    }
    '/laporan/baru': {
      id: '/laporan/baru'
      path: '/baru'
      fullPath: '/laporan/baru'
      preLoaderRoute: typeof LaporanBaruRouteImport
      parentRoute: typeof LaporanRoute
    }
    '/laporan/$id': {
      id: '/laporan/$id'
      path: '/$id'
      fullPath: '/laporan/$id'
      preLoaderRoute: typeof LaporanIdRouteImport
      parentRoute: typeof LaporanRoute
    }
    '/ajuan/baru': {
      id: '/ajuan/baru'
      path: '/ajuan/baru'
      fullPath: '/ajuan/baru'
      preLoaderRoute: typeof AjuanBaruRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ajuan/$id': {
      id: '/ajuan/$id'
      path: '/ajuan/$id'
      fullPath: '/ajuan/$id'
      preLoaderRoute: typeof AjuanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pencairan/$id/edit': {
      id: '/pencairan/$id/edit'
      path: '/edit'
      fullPath: '/pencairan/$id/edit'
      preLoaderRoute: typeof PencairanIdEditRouteImport
      parentRoute: typeof PencairanIdRoute
    }
  }
}

interface LaporanRouteChildren {
  LaporanIdRoute: typeof LaporanIdRoute
  LaporanBaruRoute: typeof LaporanBaruRoute
  LaporanIndexRoute: typeof LaporanIndexRoute
}

const LaporanRouteChildren: LaporanRouteChildren = {
  LaporanIdRoute: LaporanIdRoute,
  LaporanBaruRoute: LaporanBaruRoute,
  LaporanIndexRoute: LaporanIndexRoute,
}

const LaporanRouteWithChildren =
  LaporanRoute._addFileChildren(LaporanRouteChildren)

interface PencairanIdRouteChildren {
  PencairanIdEditRoute: typeof PencairanIdEditRoute
}

const PencairanIdRouteChildren: PencairanIdRouteChildren = {
  PencairanIdEditRoute: PencairanIdEditRoute,
}

const PencairanIdRouteWithChildren = PencairanIdRoute._addFileChildren(
  PencairanIdRouteChildren,
)

interface PencairanRouteChildren {
  PencairanIdRoute: typeof PencairanIdRouteWithChildren
  PencairanIndexRoute: typeof PencairanIndexRoute
}

const PencairanRouteChildren: PencairanRouteChildren = {
  PencairanIdRoute: PencairanIdRouteWithChildren,
  PencairanIndexRoute: PencairanIndexRoute,
}

const PencairanRouteWithChildren = PencairanRoute._addFileChildren(
  PencairanRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiRoute: AiRoute,
  ApprovalRoute: ApprovalRoute,
  AuditRoute: AuditRoute,
  AuthRoute: AuthRoute,
  LaporanRoute: LaporanRouteWithChildren,
  NotifikasiRoute: NotifikasiRoute,
  PencairanRoute: PencairanRouteWithChildren,
  PengaturanRoute: PengaturanRoute,
  PenggunaRoute: PenggunaRoute,
  AjuanIdRoute: AjuanIdRoute,
  AjuanBaruRoute: AjuanBaruRoute,
  PenggunaBaruRoute: PenggunaBaruRoute,
  AjuanIndexRoute: AjuanIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
